import 'package:dio/dio.dart';
import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';
import '../../../app/app_shell.dart';
import '../../../core/theme/app_colors.dart';
import '../../../shared/widgets/status_badge.dart';
import '../models/recovery_model.dart';
import '../services/recovery_api_service.dart';

class RecoveryPlanScreen extends StatefulWidget {
  final String recoveryId;

  const RecoveryPlanScreen({super.key, required this.recoveryId});

  @override
  State<RecoveryPlanScreen> createState() => _RecoveryPlanScreenState();
}

class _RecoveryPlanScreenState extends State<RecoveryPlanScreen> {
  final RecoveryApiService _api = RecoveryApiService();
  RecoveryRequestModel? _recovery;
  bool _isLoading = true;
  bool _isGenerating = false;
  bool _isSubmitting = false;
  bool _isTogglingChecklist = false;
  String? _errorMessage;
  String? _successMessage;

  @override
  void initState() {
    super.initState();
    _loadRecovery();
  }

  Future<void> _loadRecovery() async {
    setState(() => _isLoading = true);
    try {
      final data = await _api.getRecoveryRequest(widget.recoveryId);
      if (mounted) {
        setState(() => _recovery = data);
        if (data.plan == null && (data.status == 'Draft' || data.status == 'PlanGenerated')) {
          _generatePlan();
        }
      }
    } on DioException catch (e) {
      final body = e.response?.data;
      final msg = body is Map ? (body['error'] ?? body['title'] ?? e.message) : (e.message ?? 'Failed to load recovery plan.');
      if (mounted) setState(() => _errorMessage = msg.toString());
    } catch (e) {
      if (mounted) setState(() => _errorMessage = 'Failed to load recovery plan: $e');
    } finally {
      if (mounted) setState(() => _isLoading = false);
    }
  }

  Future<void> _generatePlan() async {
    setState(() {
      _isGenerating = true;
      _errorMessage = null;
      _successMessage = null;
    });
    try {
      final updated = await _api.generateRecoveryPlan(widget.recoveryId);
      if (mounted) {
        setState(() {
          _recovery = updated;
          _successMessage = 'Recovery plan generated by Agent 2.';
        });
      }
    } on DioException catch (e) {
      final body = e.response?.data;
      final msg = body is Map ? (body['error'] ?? body['title'] ?? e.message) : (e.message ?? 'Plan generation failed.');
      if (mounted) setState(() => _errorMessage = msg.toString());
    } catch (e) {
      if (mounted) {
        setState(() => _errorMessage = 'Plan generation failed: $e');
      }
    } finally {
      if (mounted) setState(() => _isGenerating = false);
    }
  }

  Future<void> _toggleChecklist(PreCollectionChecklistItem item, bool newValue) async {
    if (_isTogglingChecklist) return;
    // Optimistic update
    setState(() {
      _isTogglingChecklist = true;
      item.isCompleted = newValue;
      if (_recovery?.plan != null) {
        final allMandatory = _recovery!.plan!.checklist.where((c) => c.isMandatory).every((c) => c.isCompleted);
        _recovery!.plan!.isPreparationVerified = allMandatory;
      }
    });
    try {
      final resp = await _api.toggleChecklistStep(widget.recoveryId, item.id, newValue);
      if (mounted && resp != null && _recovery?.plan != null) {
        // Update isPreparationVerified from server response
        final isVerified = resp['isPreparationVerified'] as bool? ?? false;
        // Update each checklist item from server response if available
        final serverChecklist = resp['checklist'];
        if (serverChecklist is List) {
          for (final sc in serverChecklist) {
            final match = _recovery!.plan!.checklist.where((c) => c.id == (sc['id'] ?? '')).toList();
            if (match.isNotEmpty) {
              match.first.isCompleted = sc['isCompleted'] ?? false;
            }
          }
        }
        setState(() {
          _recovery!.plan!.isPreparationVerified = isVerified;
        });
      }
    } catch (_) {
      if (mounted) {
        setState(() {
          item.isCompleted = !newValue;
          if (_recovery?.plan != null) {
            final allMandatory = _recovery!.plan!.checklist.where((c) => c.isMandatory).every((c) => c.isCompleted);
            _recovery!.plan!.isPreparationVerified = allMandatory;
          }
          _errorMessage = 'Failed to update checklist step.';
        });
      }
    } finally {
      if (mounted) setState(() => _isTogglingChecklist = false);
    }
  }

  Future<void> _submitForAdminReview() async {
    final plan = _recovery?.plan;
    if (plan != null && !plan.isPreparationVerified) {
      setState(() => _errorMessage = 'Please complete all mandatory preparation checklist steps before submitting for admin review.');
      return;
    }

    setState(() {
      _isSubmitting = true;
      _errorMessage = null;
      _successMessage = null;
    });
    try {
      await _api.submitForAdminApproval(widget.recoveryId);
      if (mounted) {
        setState(() => _successMessage = 'Submitted for Admin approval.');
        await _loadRecovery();
      }
    } on DioException catch (e) {
      final body = e.response?.data;
      final msg = body is Map ? (body['error'] ?? body['title'] ?? e.message) : (e.message ?? 'Submission failed.');
      if (mounted) setState(() => _errorMessage = msg.toString());
    } catch (e) {
      if (mounted) setState(() => _errorMessage = 'Submission failed: $e');
    } finally {
      if (mounted) setState(() => _isSubmitting = false);
    }
  }

  @override
  Widget build(BuildContext context) {
    if (_isLoading) {
      return const AppShell(
        title: 'Recovery Preparation Plan',
        child: Center(child: CircularProgressIndicator(color: AppColors.primary)),
      );
    }

    if (_recovery == null) {
      return AppShell(
        title: 'Recovery Plan',
        child: Center(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              const Text('Recovery request not found', style: TextStyle(color: AppColors.slateLight)),
              const SizedBox(height: 12),
              ElevatedButton(onPressed: _loadRecovery, child: const Text('Try Again')),
            ],
          ),
        ),
      );
    }

    final recovery = _recovery!;
    final plan = recovery.plan;
    final isApproved = recovery.status == 'Approved';
    final isPendingApproval = recovery.status == 'PendingAdminApproval';
    final isRevision = recovery.status == 'RevisionRequested';
    final isDraft = recovery.status == 'Draft' || recovery.status == 'PlanGenerated';

    return AppShell(
      title: 'Recovery Preparation Plan',
      action: IconButton(
        icon: const Icon(Icons.refresh, color: AppColors.slateDark),
        tooltip: 'Reload',
        onPressed: _loadRecovery,
      ),
      child: SingleChildScrollView(
        padding: const EdgeInsets.all(16),
        child: Center(
          child: ConstrainedBox(
            constraints: const BoxConstraints(maxWidth: 800),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.stretch,
              children: [
                // Alerts
                if (_errorMessage != null) ...[
                  Container(
                    padding: const EdgeInsets.all(12),
                    margin: const EdgeInsets.only(bottom: 12),
                    decoration: BoxDecoration(
                      color: AppColors.rose50,
                      borderRadius: BorderRadius.circular(8),
                      border: Border.all(color: AppColors.rose500.withAlpha(80)),
                    ),
                    child: Row(
                      children: [
                        const Icon(Icons.error_outline, color: AppColors.rose500, size: 18),
                        const SizedBox(width: 10),
                        Expanded(child: Text(_errorMessage!, style: const TextStyle(color: AppColors.rose700, fontSize: 13))),
                      ],
                    ),
                  ),
                ],

                if (_successMessage != null) ...[
                  Container(
                    padding: const EdgeInsets.all(12),
                    margin: const EdgeInsets.only(bottom: 12),
                    decoration: BoxDecoration(
                      color: AppColors.primarySubtle,
                      borderRadius: BorderRadius.circular(8),
                      border: Border.all(color: AppColors.primary.withAlpha(80)),
                    ),
                    child: Row(
                      children: [
                        const Icon(Icons.check_circle_outline, color: AppColors.primary, size: 18),
                        const SizedBox(width: 10),
                        Expanded(child: Text(_successMessage!, style: const TextStyle(color: AppColors.primary, fontSize: 13, fontWeight: FontWeight.w600))),
                      ],
                    ),
                  ),
                ],

                // Status banners
                if (isApproved) ...[
                  Container(
                    padding: const EdgeInsets.all(14),
                    margin: const EdgeInsets.only(bottom: 14),
                    decoration: BoxDecoration(
                      color: const Color(0xFFF0FDF4),
                      borderRadius: BorderRadius.circular(10),
                      border: Border.all(color: const Color(0xFF86EFAC)),
                    ),
                    child: const Row(
                      children: [
                        Icon(Icons.shield_outlined, color: Color(0xFF166534), size: 20),
                        SizedBox(width: 10),
                        Expanded(
                          child: Column(
                            crossAxisAlignment: CrossAxisAlignment.start,
                            children: [
                              Text('Plan Approved by Admin', style: TextStyle(fontWeight: FontWeight.w700, fontSize: 13, color: Color(0xFF166534))),
                              Text('Your recovery plan has been verified. Keep your Handover Pass ready for pickup.', style: TextStyle(fontSize: 12, color: Color(0xFF15803D))),
                            ],
                          ),
                        ),
                      ],
                    ),
                  ),
                ],

                if (isPendingApproval) ...[
                  Container(
                    padding: const EdgeInsets.all(14),
                    margin: const EdgeInsets.only(bottom: 14),
                    decoration: BoxDecoration(
                      color: const Color(0xFFEFF6FF),
                      borderRadius: BorderRadius.circular(10),
                      border: Border.all(color: const Color(0xFFBFDBFE)),
                    ),
                    child: const Row(
                      children: [
                        Icon(Icons.shield_outlined, color: Color(0xFF1D4ED8), size: 20),
                        SizedBox(width: 10),
                        Expanded(
                          child: Column(
                            crossAxisAlignment: CrossAxisAlignment.start,
                            children: [
                              Text('Awaiting Admin Review', style: TextStyle(fontWeight: FontWeight.w700, fontSize: 13, color: Color(0xFF1E40AF))),
                              Text('Your recovery plan has been submitted and is undergoing human review.', style: TextStyle(fontSize: 12, color: Color(0xFF1D4ED8))),
                            ],
                          ),
                        ),
                      ],
                    ),
                  ),
                ],

                if (isRevision) ...[
                  Container(
                    padding: const EdgeInsets.all(14),
                    margin: const EdgeInsets.only(bottom: 14),
                    decoration: BoxDecoration(
                      color: const Color(0xFFFFFBEB),
                      borderRadius: BorderRadius.circular(10),
                      border: Border.all(color: const Color(0xFFFDE68A)),
                    ),
                    child: const Row(
                      children: [
                        Icon(Icons.warning_amber_rounded, color: Color(0xFFD97706), size: 20),
                        SizedBox(width: 10),
                        Expanded(
                          child: Column(
                            crossAxisAlignment: CrossAxisAlignment.start,
                            children: [
                              Text('Revision Requested by Admin', style: TextStyle(fontWeight: FontWeight.w700, fontSize: 13, color: Color(0xFF92400E))),
                              Text('Please review the feedback and regenerate or resubmit the plan.', style: TextStyle(fontSize: 12, color: Color(0xFFA16207))),
                            ],
                          ),
                        ),
                      ],
                    ),
                  ),
                ],

                // Top Overview Card
                Card(
                  margin: const EdgeInsets.only(bottom: 16),
                  child: Padding(
                    padding: const EdgeInsets.all(18),
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        Row(
                          mainAxisAlignment: MainAxisAlignment.spaceBetween,
                          children: [
                            Expanded(
                              child: Text(
                                recovery.item?.name ?? 'Recovery Item',
                                style: const TextStyle(fontSize: 18, fontWeight: FontWeight.w800, color: AppColors.slateDark),
                              ),
                            ),
                            StatusBadge(label: recovery.status),
                          ],
                        ),
                        const SizedBox(height: 6),
                        Container(
                          padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 3),
                          decoration: BoxDecoration(
                            color: AppColors.primarySubtle,
                            borderRadius: BorderRadius.circular(6),
                          ),
                          child: Text(
                            'Route: ${recovery.selectedRoute}',
                            style: const TextStyle(fontSize: 12, color: AppColors.primary, fontWeight: FontWeight.w700),
                          ),
                        ),
                      ],
                    ),
                  ),
                ),

                // Plan section
                Card(
                  margin: const EdgeInsets.only(bottom: 16),
                  child: Padding(
                    padding: const EdgeInsets.all(18),
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        const Row(
                          children: [
                            Icon(Icons.auto_awesome, color: AppColors.primary, size: 20),
                            SizedBox(width: 8),
                            Text(
                              'Agent 2 Preparation Plan',
                              style: TextStyle(fontSize: 16, fontWeight: FontWeight.w800, color: AppColors.slateDark),
                            ),
                          ],
                        ),
                        const SizedBox(height: 14),

                        if (plan == null && !_isGenerating) ...[
                          // No plan yet — show generate button
                          Center(
                            child: Column(
                              children: [
                                const Icon(Icons.auto_awesome, color: AppColors.primary, size: 36),
                                const SizedBox(height: 12),
                                const Text(
                                  'Agent 2 Preparation Plan Needed',
                                  style: TextStyle(fontWeight: FontWeight.w700, fontSize: 15, color: AppColors.slateDark),
                                ),
                                const SizedBox(height: 6),
                                Text(
                                  'Agent 2 generates safe packaging guidelines, data wipe reminders, and hazardous material precautions for the ${recovery.selectedRoute} route.',
                                  textAlign: TextAlign.center,
                                  style: const TextStyle(fontSize: 13, color: AppColors.slateLight, height: 1.4),
                                ),
                                const SizedBox(height: 16),
                                ElevatedButton.icon(
                                  onPressed: _generatePlan,
                                  icon: const Icon(Icons.auto_awesome, size: 16, color: Colors.white),
                                  label: const Text(
                                    'Generate Preparation Plan',
                                    style: TextStyle(fontWeight: FontWeight.bold, fontSize: 14, color: Colors.white),
                                  ),
                                  style: ElevatedButton.styleFrom(
                                    backgroundColor: AppColors.primary,
                                    padding: const EdgeInsets.symmetric(horizontal: 20, vertical: 14),
                                    shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(10)),
                                  ),
                                ),
                              ],
                            ),
                          ),
                        ] else if (_isGenerating) ...[
                          const Center(
                            child: Column(
                              children: [
                                CircularProgressIndicator(color: AppColors.primary),
                                SizedBox(height: 16),
                                Text(
                                  'Agent 2 is Synthesizing Safe Recovery Plan...',
                                  style: TextStyle(fontWeight: FontWeight.w700, fontSize: 15, color: AppColors.slateDark),
                                ),
                                SizedBox(height: 6),
                                Text(
                                  'Formulating hazardous material handling, data sterilization checklist, and preparation sequence.',
                                  textAlign: TextAlign.center,
                                  style: TextStyle(color: AppColors.slateLight, fontSize: 12),
                                ),
                              ],
                            ),
                          ),
                        ] else if (plan != null) ...[
                          // Plan summary grid
                          Container(
                            padding: const EdgeInsets.all(12),
                            decoration: BoxDecoration(
                              color: AppColors.surfaceSubtle,
                              borderRadius: BorderRadius.circular(8),
                            ),
                            child: Row(
                              children: [
                                Expanded(
                                  child: Column(
                                    crossAxisAlignment: CrossAxisAlignment.start,
                                    children: [
                                      const Text('Suitability Rating', style: TextStyle(fontSize: 11, color: AppColors.slateLight, fontWeight: FontWeight.w500)),
                                      const SizedBox(height: 2),
                                      Text(plan.suitability, style: const TextStyle(fontWeight: FontWeight.w700, fontSize: 13, color: AppColors.slateDark)),
                                    ],
                                  ),
                                ),
                                const SizedBox(width: 12),
                                Expanded(
                                  child: Column(
                                    crossAxisAlignment: CrossAxisAlignment.start,
                                    children: [
                                      const Text('Required Partner Facility', style: TextStyle(fontSize: 11, color: AppColors.slateLight, fontWeight: FontWeight.w500)),
                                      const SizedBox(height: 2),
                                      Text(plan.requiredPartnerType, style: const TextStyle(fontWeight: FontWeight.w700, fontSize: 13, color: AppColors.slateDark)),
                                    ],
                                  ),
                                ),
                              ],
                            ),
                          ),
                          const SizedBox(height: 14),

                          // Summary
                          const Text('Preparation Summary', style: TextStyle(fontSize: 12, fontWeight: FontWeight.w600, color: AppColors.slateLight)),
                          const SizedBox(height: 6),
                          Text(plan.summary, style: const TextStyle(fontSize: 13, color: AppColors.slate, height: 1.5)),
                          const SizedBox(height: 14),

                          // Recommended Steps
                          if (plan.steps.isNotEmpty) ...[
                            const Text('Recommended Action Steps', style: TextStyle(fontSize: 13, fontWeight: FontWeight.w700, color: AppColors.slateDark)),
                            const SizedBox(height: 8),
                            ...plan.steps.asMap().entries.map((e) => Container(
                                  margin: const EdgeInsets.only(bottom: 8),
                                  padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 10),
                                  decoration: BoxDecoration(
                                    color: AppColors.surfaceSubtle,
                                    borderRadius: BorderRadius.circular(8),
                                    border: Border.all(color: AppColors.border),
                                  ),
                                  child: Row(
                                    crossAxisAlignment: CrossAxisAlignment.start,
                                    children: [
                                      Text('${(e.key + 1).toString().padLeft(2, '0')}.', style: const TextStyle(fontWeight: FontWeight.w700, color: AppColors.primary, fontSize: 13)),
                                      const SizedBox(width: 10),
                                      Expanded(child: Text(e.value.stepText, style: const TextStyle(fontSize: 13, color: AppColors.slate))),
                                    ],
                                  ),
                                )),
                            const SizedBox(height: 8),
                          ],

                          // Admin handling instructions
                          if (plan.adminHandlingInstructions != null && plan.adminHandlingInstructions!.isNotEmpty) ...[
                            Container(
                              padding: const EdgeInsets.all(14),
                              margin: const EdgeInsets.only(bottom: 14),
                              decoration: BoxDecoration(
                                color: const Color(0xFFEFF6FF),
                                borderRadius: BorderRadius.circular(8),
                                border: Border(
                                  left: const BorderSide(color: Color(0xFF2563EB), width: 4),
                                  right: BorderSide(color: const Color(0xFFBFDBFE).withAlpha(180)),
                                  top: BorderSide(color: const Color(0xFFBFDBFE).withAlpha(180)),
                                  bottom: BorderSide(color: const Color(0xFFBFDBFE).withAlpha(180)),
                                ),
                              ),
                              child: Column(
                                crossAxisAlignment: CrossAxisAlignment.start,
                                children: [
                                  const Row(
                                    children: [
                                      Icon(Icons.shield_outlined, color: Color(0xFF2563EB), size: 16),
                                      SizedBox(width: 6),
                                      Text('Admin Special Handling Directives:', style: TextStyle(fontSize: 12, fontWeight: FontWeight.w700, color: Color(0xFF1E40AF))),
                                    ],
                                  ),
                                  const SizedBox(height: 6),
                                  Text(plan.adminHandlingInstructions!, style: const TextStyle(fontSize: 12, color: Color(0xFF1E3A8A), height: 1.5)),
                                ],
                              ),
                            ),
                          ],
                        ],
                      ],
                    ),
                  ),
                ),

                // Safety Hazards (outside plan card for prominence)
                if (plan != null && plan.safetyNotes.isNotEmpty) ...[
                  Container(
                    padding: const EdgeInsets.all(16),
                    margin: const EdgeInsets.only(bottom: 16),
                    decoration: BoxDecoration(
                      color: const Color(0xFFFFFBEB),
                      borderRadius: BorderRadius.circular(12),
                      border: Border.all(color: const Color(0xFFFDE68A)),
                    ),
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        const Row(
                          children: [
                            Icon(Icons.warning_amber_rounded, color: Color(0xFFD97706), size: 20),
                            SizedBox(width: 8),
                            Text(
                              'Safety & Hazardous Material Precautions',
                              style: TextStyle(fontWeight: FontWeight.w800, fontSize: 14, color: Color(0xFF92400E)),
                            ),
                          ],
                        ),
                        const SizedBox(height: 8),
                        ...plan.safetyNotes.map((n) => Padding(
                              padding: const EdgeInsets.only(bottom: 6),
                              child: Row(
                                crossAxisAlignment: CrossAxisAlignment.start,
                                children: [
                                  const Text('• ', style: TextStyle(color: Color(0xFFD97706), fontWeight: FontWeight.bold)),
                                  Expanded(
                                    child: Text(n.noteText, style: const TextStyle(fontSize: 12, color: Color(0xFF78350F), height: 1.4)),
                                  ),
                                ],
                              ),
                            )),
                      ],
                    ),
                  ),
                ],

                // Pre-Collection Readiness Checklist
                if (plan != null && plan.checklist.isNotEmpty) ...[
                  Builder(builder: (context) {
                    final total = plan.checklist.length;
                    final completed = plan.checklist.where((c) => c.isCompleted).length;
                    final pct = (completed / total * 100).round();
                    final isVerified = plan.isPreparationVerified;
                    final canEdit = isDraft || isRevision;

                    return Container(
                      padding: const EdgeInsets.all(16),
                      margin: const EdgeInsets.only(bottom: 16),
                      decoration: BoxDecoration(
                        color: const Color(0xFFF8FAFC),
                        borderRadius: BorderRadius.circular(12),
                        border: Border.all(color: isVerified ? const Color(0xFFBBF7D0) : AppColors.border),
                      ),
                      child: Column(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: [
                          Row(
                            children: [
                              const Expanded(
                                child: Text(
                                  'Pre-Collection Readiness Checklist',
                                  style: TextStyle(fontWeight: FontWeight.w800, fontSize: 14, color: AppColors.slateDark),
                                ),
                              ),
                              if (isVerified)
                                Container(
                                  padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 3),
                                  decoration: BoxDecoration(color: const Color(0xFFDCFCE7), borderRadius: BorderRadius.circular(4)),
                                  child: const Text('✓ 100% Ready', style: TextStyle(color: Color(0xFF166534), fontSize: 11, fontWeight: FontWeight.w700)),
                                )
                              else
                                Container(
                                  padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 3),
                                  decoration: BoxDecoration(color: const Color(0xFFFEF3C7), borderRadius: BorderRadius.circular(4)),
                                  child: Text('$completed/$total Completed', style: const TextStyle(color: Color(0xFF92400E), fontSize: 11, fontWeight: FontWeight.w600)),
                                ),
                            ],
                          ),
                          const SizedBox(height: 4),
                          const Text('All mandatory items required before submission', style: TextStyle(fontSize: 11, color: AppColors.slateLight)),
                          const SizedBox(height: 10),

                          // Progress bar
                          ClipRRect(
                            borderRadius: BorderRadius.circular(999),
                            child: LinearProgressIndicator(
                              value: pct / 100.0,
                              backgroundColor: const Color(0xFFE2E8F0),
                              color: isVerified ? const Color(0xFF16A34A) : AppColors.primary,
                              minHeight: 6,
                            ),
                          ),
                          const SizedBox(height: 12),

                          // Checklist items
                          ...plan.checklist.map((item) => GestureDetector(
                                onTap: canEdit ? () => _toggleChecklist(item, !item.isCompleted) : null,
                                child: Container(
                                  margin: const EdgeInsets.only(bottom: 8),
                                  padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 10),
                                  decoration: BoxDecoration(
                                    color: item.isCompleted ? const Color(0xFFF0FDF4) : Colors.white,
                                    borderRadius: BorderRadius.circular(8),
                                    border: Border.all(color: item.isCompleted ? const Color(0xFFBBF7D0) : const Color(0xFFE2E8F0)),
                                  ),
                                  child: Row(
                                    crossAxisAlignment: CrossAxisAlignment.start,
                                    children: [
                                      Icon(
                                        item.isCompleted ? Icons.check_box_rounded : Icons.check_box_outline_blank_rounded,
                                        color: item.isCompleted ? const Color(0xFF16A34A) : const Color(0xFF94A3B8),
                                        size: 20,
                                      ),
                                      const SizedBox(width: 10),
                                      Expanded(
                                        child: Column(
                                          crossAxisAlignment: CrossAxisAlignment.start,
                                          children: [
                                            Row(
                                              children: [
                                                Expanded(
                                                  child: Text(
                                                    item.title,
                                                    style: TextStyle(
                                                      fontWeight: FontWeight.w600,
                                                      fontSize: 13,
                                                      color: item.isCompleted ? const Color(0xFF166534) : AppColors.slateDark,
                                                    ),
                                                  ),
                                                ),
                                                if (item.isMandatory)
                                                  Container(
                                                    padding: const EdgeInsets.symmetric(horizontal: 5, vertical: 1),
                                                    decoration: BoxDecoration(color: const Color(0xFFFEE2E2), borderRadius: BorderRadius.circular(3)),
                                                    child: const Text('Required', style: TextStyle(fontSize: 10, color: Color(0xFFDC2626), fontWeight: FontWeight.w600)),
                                                  ),
                                              ],
                                            ),
                                            if (item.description.isNotEmpty) ...[
                                              const SizedBox(height: 2),
                                              Text(item.description, style: const TextStyle(fontSize: 11, color: AppColors.slateLight, height: 1.4)),
                                            ],
                                          ],
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              )),
                        ],
                      ),
                    );
                  }),
                ],

                // Bottom Action Bar
                if (plan != null) ...[
                  const Divider(),
                  const SizedBox(height: 12),
                  Row(
                    mainAxisAlignment: MainAxisAlignment.spaceBetween,
                    children: [
                      // Left: Regenerate (only in draft)
                      if (isDraft)
                        OutlinedButton.icon(
                          onPressed: _isGenerating ? null : _generatePlan,
                          icon: const Icon(Icons.auto_awesome, size: 14),
                          label: const Text('Regenerate Plan'),
                          style: OutlinedButton.styleFrom(
                            padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 10),
                            foregroundColor: AppColors.primary,
                            side: const BorderSide(color: AppColors.primary),
                          ),
                        )
                      else
                        const SizedBox(),

                      // Right: Submit for Admin Review or Proceed to Matching
                      if (isApproved)
                        Expanded(
                          child: Padding(
                            padding: const EdgeInsets.only(left: 8),
                            child: ElevatedButton.icon(
                              onPressed: () {
                                context.push('/matching-partners?recoveryId=${recovery.id}');
                              },
                              icon: const Icon(Icons.handshake_outlined, color: Colors.white),
                              label: const Text(
                                'Proceed to Certified Partner Matching',
                                style: TextStyle(fontWeight: FontWeight.bold, fontSize: 14, color: Colors.white),
                              ),
                              style: ElevatedButton.styleFrom(
                                backgroundColor: AppColors.primary,
                                padding: const EdgeInsets.symmetric(vertical: 14),
                                shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(10)),
                              ),
                            ),
                          ),
                        )
                      else if (isDraft || isRevision) ...[
                        if (!(plan.isPreparationVerified))
                          Row(
                            mainAxisSize: MainAxisSize.min,
                            children: [
                              const Text(
                                'Check all required items to enable review: ',
                                style: TextStyle(fontSize: 12, color: AppColors.slateLight),
                              ),
                              Tooltip(
                                message: 'Complete all required checklist items first',
                                child: ElevatedButton.icon(
                                  onPressed: null,
                                  icon: const Icon(Icons.lock_outline, size: 16, color: Colors.white70),
                                  label: const Text('Submit for Admin Review', style: TextStyle(color: Colors.white70, fontWeight: FontWeight.bold)),
                                  style: ElevatedButton.styleFrom(
                                    backgroundColor: AppColors.primary.withAlpha(90),
                                    padding: const EdgeInsets.symmetric(horizontal: 14, vertical: 14),
                                    shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(10)),
                                  ),
                                ),
                              ),
                            ],
                          )
                        else
                          ElevatedButton.icon(
                            onPressed: _isSubmitting ? null : _submitForAdminReview,
                            icon: _isSubmitting
                                ? const SizedBox(width: 16, height: 16, child: CircularProgressIndicator(strokeWidth: 2, color: Colors.white))
                                : const Icon(Icons.shield_outlined, size: 16, color: Colors.white),
                            label: Text(
                              _isSubmitting ? 'Submitting...' : 'Submit for Admin Review',
                              style: const TextStyle(fontWeight: FontWeight.bold, color: Colors.white),
                            ),
                            style: ElevatedButton.styleFrom(
                              backgroundColor: AppColors.primary,
                              padding: const EdgeInsets.symmetric(horizontal: 14, vertical: 14),
                              shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(10)),
                            ),
                          ),
                      ],
                    ],
                  ),
                ],
              ],
            ),
          ),
        ),
      ),
    );
  }
}
