import React, { useEffect, useState } from 'react'
import { useParams, useNavigate, Link } from 'react-router'
import { ArrowLeft, Sparkles, AlertCircle, CheckCircle2, ArrowRight, ShieldCheck, AlertTriangle, CheckSquare, Square, Lock, HelpCircle } from 'lucide-react'
import { apiClient } from '../../../shared/services/apiClient.js'
import { StatusChip } from '../../../shared/components/StatusChip.jsx'
import { TopBar } from '../../../shared/components/TopBar.jsx'
import { HandoverPassCard } from '../../../shared/components/HandoverPassCard.jsx'

export function RecoveryPlanPage() {
  const { id } = useParams()
  const navigate = useNavigate()
  const [recovery, setRecovery] = useState(null)
  const [loading, setLoading] = useState(true)
  const [generating, setGenerating] = useState(false)
  const [submitting, setSubmitting] = useState(false)
  const [togglingChecklist, setTogglingChecklist] = useState(false)
  const [error, setError] = useState('')
  const [success, setSuccess] = useState('')

  useEffect(() => {
    loadRecovery()
  }, [id])

  const loadRecovery = async () => {
    try {
      setLoading(true)
      const res = await apiClient.get(`/api/recovery/${id}`)
      setRecovery(res.data)
    } catch {
      setError('Failed to load recovery plan.')
    } finally {
      setLoading(false)
    }
  }

  // Generate Plan with Agent 2
  const handleGeneratePlan = async () => {
    setGenerating(true)
    setError('')
    try {
      await apiClient.post(`/api/recovery/${id}/plan`)
      setSuccess('Recovery plan generated by Agent 2.')
      await loadRecovery()
    } catch (err) {
      console.error('Generate plan error:', err)
      setError(
        err.response?.data?.error ||
        err.response?.data?.title ||
        err.message ||
        'Plan generation failed.'
      )
    } finally {
      setGenerating(false)
    }
  }

  // Toggle checklist step
  const handleToggleChecklist = async (stepId, currentStatus) => {
    try {
      setTogglingChecklist(true)
      const res = await apiClient.patch(`/api/recovery/${id}/checklist`, {
        stepId,
        isCompleted: !currentStatus
      })
      setRecovery(prev => {
        if (!prev || !prev.plan) return prev
        return {
          ...prev,
          plan: {
            ...prev.plan,
            checklist: res.data.checklist,
            isPreparationVerified: res.data.isPreparationVerified
          }
        }
      })
    } catch {
      setError('Failed to update preparation checklist.')
    } finally {
      setTogglingChecklist(false)
    }
  }

  // Submit for Admin Review
  const handleSubmit = async () => {
    if (plan && !plan.isPreparationVerified) {
      setError('Please complete all mandatory pre-collection preparation checklist steps before submitting for admin review.')
      return
    }

    setSubmitting(true)
    setError('')
    try {
      await apiClient.post(`/api/recovery/${id}/submit`)
      setSuccess('Submitted for Admin approval.')
      await loadRecovery()
    } catch (err) {
      setError(err.response?.data?.error || 'Submission failed.')
    } finally {
      setSubmitting(false)
    }
  }

  if (loading) {
    return (
      <div style={{ padding: '3rem', textAlign: 'center' }}>
        <p style={{ color: 'var(--text-muted)' }}>Loading recovery details...</p>
      </div>
    )
  }

  if (!recovery) {
    return (
      <div style={{ padding: '3rem', textAlign: 'center' }}>
        <p style={{ color: 'var(--error)' }}>Recovery request not found.</p>
        <Link to="/recovery" className="btn btn-secondary" style={{ marginTop: '1rem' }}>Back to Recoveries</Link>
      </div>
    )
  }

  const plan = recovery.plan
  const isApproved = recovery.status === 'Approved'
  const isPendingApproval = recovery.status === 'PendingAdminApproval'
  const isRevision = recovery.status === 'RevisionRequested'
  const isDraft = recovery.status === 'Draft' || recovery.status === 'PlanGenerated'

  return (
    <>
      <TopBar
        title="Recovery Preparation Plan"
        action={
          <Link to="/recovery" className="btn btn-secondary btn-sm">
            <ArrowLeft size={16} />
            <span>Back to Recoveries</span>
          </Link>
        }
      />

      <div className="content-container" style={{ maxWidth: '900px' }}>
        {error && (
          <div className="alert alert-error">
            <AlertCircle size={18} />
            <span>{error}</span>
          </div>
        )}

        {success && (
          <div className="alert alert-success">
            <CheckCircle2 size={18} />
            <span>{success}</span>
          </div>
        )}

        {/* Approval Banner & Digital Handover Pass */}
        {isApproved && (
          <>
            <div className="alert alert-success" style={{ display: 'flex', alignItems: 'center', gap: '0.75rem' }}>
              <ShieldCheck size={24} />
              <div>
                <div style={{ fontWeight: 600 }}>Plan Approved by Admin</div>
                <div style={{ fontSize: '0.8125rem' }}>Your recovery preparation plan has been verified and approved by the admin. Keep your Digital Handover Pass ready for pickup.</div>
              </div>
            </div>

            <HandoverPassCard recovery={recovery} />
          </>
        )}

        {isPendingApproval && (
          <div className="alert alert-info">
            <ShieldCheck size={20} />
            <div>
              <div style={{ fontWeight: 600 }}>Awaiting Admin Review</div>
              <div style={{ fontSize: '0.8125rem' }}>Your recovery plan has been submitted and is undergoing human review.</div>
            </div>
          </div>
        )}

        {isRevision && (
          <div className="alert alert-warning">
            <AlertTriangle size={20} />
            <div>
              <div style={{ fontWeight: 600 }}>Revision Requested by Admin</div>
              <div style={{ fontSize: '0.8125rem' }}>Please review the feedback and regenerate or resubmit the plan.</div>
            </div>
          </div>
        )}

        <div className="card" style={{ marginBottom: '1.5rem' }}>
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: '1.25rem' }}>
            <div>
              <h2 style={{ fontSize: '1.375rem' }}>{recovery.item?.name}</h2>
              <div style={{ color: 'var(--text-muted)', fontSize: '0.875rem', marginTop: '0.25rem' }}>
                Category: <strong>{recovery.item?.category?.name}</strong> • Brand: {recovery.item?.brand || 'N/A'}
              </div>
            </div>
            <div style={{ display: 'flex', gap: '0.5rem', alignItems: 'center' }}>
              <StatusChip status={recovery.selectedRoute} type="route" />
              <StatusChip status={recovery.status} />
            </div>
          </div>

          {!plan ? (
            <div style={{ textAlign: 'center', padding: '2.5rem 1rem' }}>
              <Sparkles size={36} color="var(--primary)" style={{ margin: '0 auto 1rem' }} />
              <h3 style={{ marginBottom: '0.5rem' }}>Agent 2 Preparation Plan Needed</h3>
              <p style={{ color: 'var(--text-muted)', maxWidth: '440px', margin: '0 auto 1.5rem', fontSize: '0.875rem' }}>
                Agent 2 generates safe packaging guidelines, data wipe reminders, and hazardous material precautions for the <strong>{recovery.selectedRoute}</strong> route.
              </p>
              <button
                onClick={handleGeneratePlan}
                disabled={generating}
                className="btn btn-primary"
              >
                <Sparkles size={16} />
                <span>{generating ? 'Generating Plan...' : 'Generate Preparation Plan'}</span>
              </button>
            </div>
          ) : (
            <div>
              <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '1rem', padding: '1rem', background: 'var(--surface-subtle)', borderRadius: 'var(--radius-sm)', marginBottom: '1.5rem' }}>
                <div>
                  <div style={{ fontSize: '0.75rem', color: 'var(--text-muted)', fontWeight: 500 }}>Suitability Rating</div>
                  <div style={{ fontWeight: 600, fontSize: '0.9375rem' }}>{plan.suitability}</div>
                </div>
                <div>
                  <div style={{ fontSize: '0.75rem', color: 'var(--text-muted)', fontWeight: 500 }}>Required Partner Facility</div>
                  <div style={{ fontWeight: 600, fontSize: '0.9375rem' }}>{plan.requiredPartnerType}</div>
                </div>
              </div>

              <div style={{ marginBottom: '1.5rem' }}>
                <div style={{ fontSize: '0.8125rem', fontWeight: 600, color: 'var(--text-muted)', marginBottom: '0.375rem' }}>
                  Preparation Summary
                </div>
                <p style={{ fontSize: '0.875rem', lineHeight: 1.6 }}>{plan.summary}</p>
              </div>

              {/* Steps */}
              <div style={{ marginBottom: '1.5rem' }}>
                <div style={{ fontSize: '0.875rem', fontWeight: 600, marginBottom: '0.75rem' }}>
                  Recommended Action Steps
                </div>
                <div style={{ display: 'flex', flexDirection: 'column', gap: '0.625rem' }}>
                  {plan.steps && plan.steps.map((step, idx) => (
                    <div key={idx} style={{ display: 'flex', gap: '0.75rem', background: '#F8FAFC', padding: '0.75rem 1rem', borderRadius: 'var(--radius-sm)', border: '1px solid var(--border-light)' }}>
                      <span style={{ fontWeight: 700, color: 'var(--primary)', fontSize: '0.875rem' }}>
                        {(idx + 1).toString().padStart(2, '0')}.
                      </span>
                      <span style={{ fontSize: '0.875rem' }}>{step.stepText}</span>
                    </div>
                  ))}
                </div>
              </div>

              {/* Safety Notes */}
              {plan.safetyNotes && plan.safetyNotes.length > 0 && (
                <div style={{ marginBottom: '1.5rem' }}>
                  <div style={{ fontSize: '0.875rem', fontWeight: 600, marginBottom: '0.75rem', display: 'flex', alignItems: 'center', gap: '0.375rem', color: 'var(--warning)' }}>
                    <AlertTriangle size={16} />
                    <span>Safety & Hazardous Material Precautions</span>
                  </div>
                  <div style={{ display: 'flex', flexDirection: 'column', gap: '0.5rem' }}>
                    {plan.safetyNotes.map((note, idx) => (
                      <div key={idx} style={{ fontSize: '0.8125rem', color: '#78350F', background: '#FFFBEB', padding: '0.625rem 0.875rem', borderRadius: 'var(--radius-sm)', border: '1px solid #FDE68A' }}>
                        • {note.noteText}
                      </div>
                    ))}
                  </div>
                </div>
              )}

              {/* Feature 5: Admin Special Handling Instructions (if added by Admin) */}
              {plan.adminHandlingInstructions && (
                <div style={{
                  marginBottom: '1.5rem',
                  background: '#EFF6FF',
                  border: '1px solid #BFDBFE',
                  borderLeft: '4px solid #2563EB',
                  padding: '1rem 1.25rem',
                  borderRadius: 'var(--radius-sm)'
                }}>
                  <div style={{ fontSize: '0.875rem', fontWeight: 700, color: '#1E40AF', marginBottom: '0.35rem', display: 'flex', alignItems: 'center', gap: '0.375rem' }}>
                    <ShieldCheck size={18} color="#2563EB" />
                    <span>Admin Special Handling & Safety Directives:</span>
                  </div>
                  <p style={{ margin: 0, fontSize: '0.8125rem', color: '#1E3A8A', lineHeight: 1.5 }}>
                    {plan.adminHandlingInstructions}
                  </p>
                </div>
              )}

              {/* Feature 2: Interactive Pre-Collection Readiness Checklist */}
              {plan.checklist && plan.checklist.length > 0 && (() => {
                const total = plan.checklist.length
                const completed = plan.checklist.filter(c => c.isCompleted).length
                const pct = Math.round((completed / total) * 100)
                const isVerified = plan.isPreparationVerified

                return (
                  <div style={{
                    marginBottom: '1.75rem',
                    background: '#F8FAFC',
                    border: `1px solid ${isVerified ? '#BBF7D0' : 'var(--border-light)'}`,
                    borderRadius: 'var(--radius-md)',
                    padding: '1.25rem'
                  }}>
                    <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '0.75rem', flexWrap: 'wrap', gap: '0.5rem' }}>
                      <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
                        <div style={{ fontWeight: 700, fontSize: '0.9375rem', color: 'var(--dark)' }}>
                          Pre-Collection Readiness Checklist
                        </div>
                        {isVerified ? (
                          <span style={{ background: '#DCFCE7', color: '#166534', fontSize: '0.75rem', fontWeight: 700, padding: '0.15rem 0.5rem', borderRadius: '4px' }}>
                            ✓ 100% Ready
                          </span>
                        ) : (
                          <span style={{ background: '#FEF3C7', color: '#92400E', fontSize: '0.75rem', fontWeight: 600, padding: '0.15rem 0.5rem', borderRadius: '4px' }}>
                            {completed}/{total} Completed
                          </span>
                        )}
                      </div>
                      <span style={{ fontSize: '0.75rem', color: 'var(--text-muted)' }}>
                        All mandatory items required before submission
                      </span>
                    </div>

                    {/* Progress Bar */}
                    <div style={{ width: '100%', height: '6px', background: '#E2E8F0', borderRadius: '999px', overflow: 'hidden', marginBottom: '1rem' }}>
                      <div style={{ width: `${pct}%`, height: '100%', background: isVerified ? '#16A34A' : 'var(--primary)', transition: 'width 0.3s ease' }} />
                    </div>

                    {/* Checklist Items */}
                    <div style={{ display: 'flex', flexDirection: 'column', gap: '0.625rem' }}>
                      {plan.checklist.map((step) => {
                        const canEdit = isDraft || isRevision
                        return (
                          <div
                            key={step.id}
                            onClick={() => canEdit && handleToggleChecklist(step.id, step.isCompleted)}
                            style={{
                              display: 'flex',
                              alignItems: 'flex-start',
                              gap: '0.75rem',
                              padding: '0.75rem 1rem',
                              background: step.isCompleted ? '#F0FDF4' : '#FFFFFF',
                              border: `1px solid ${step.isCompleted ? '#BBF7D0' : '#E2E8F0'}`,
                              borderRadius: 'var(--radius-sm)',
                              cursor: canEdit ? 'pointer' : 'default',
                              transition: 'all 0.15s ease'
                            }}
                          >
                            <div style={{ marginTop: '2px', flexShrink: 0 }}>
                              {step.isCompleted ? (
                                <CheckSquare size={18} color="#16A34A" />
                              ) : (
                                <Square size={18} color="#94A3B8" />
                              )}
                            </div>
                            <div style={{ flex: 1 }}>
                              <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', marginBottom: '0.15rem' }}>
                                <span style={{
                                  fontWeight: 600,
                                  fontSize: '0.875rem',
                                  color: step.isCompleted ? '#166534' : 'var(--dark)',
                                  textDecoration: step.isCompleted ? 'none' : 'none'
                                }}>
                                  {step.title}
                                </span>
                                {step.isMandatory && (
                                  <span style={{ fontSize: '0.6875rem', color: '#DC2626', fontWeight: 600, background: '#FEE2E2', padding: '0.1rem 0.35rem', borderRadius: '3px' }}>
                                    Required
                                  </span>
                                )}
                              </div>
                              <p style={{ margin: 0, fontSize: '0.8125rem', color: 'var(--text-muted)', lineHeight: 1.4 }}>
                                {step.description}
                              </p>
                            </div>
                          </div>
                        )
                      })}
                    </div>
                  </div>
                )
              })()}

              {/* Submission / Next Step Action Bar */}
              <div style={{ borderTop: '1px solid var(--border-light)', paddingTop: '1.5rem', display: 'flex', justifyContent: 'space-between', alignItems: 'center', flexWrap: 'wrap', gap: '1rem' }}>
                <div>
                  {isDraft && (
                    <button
                      onClick={handleGeneratePlan}
                      disabled={generating}
                      className="btn btn-secondary btn-sm"
                    >
                      <Sparkles size={14} />
                      <span>Regenerate Plan</span>
                    </button>
                  )}
                </div>

                <div style={{ display: 'flex', alignItems: 'center', gap: '0.75rem' }}>
                  {(isDraft || isRevision) && (
                    <>
                      {!plan.isPreparationVerified ? (
                        <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
                          <span style={{ fontSize: '0.75rem', color: 'var(--text-muted)' }}>
                            Check all required items to enable review:
                          </span>
                          <button
                            disabled={true}
                            className="btn btn-secondary"
                            style={{ opacity: 0.6, cursor: 'not-allowed' }}
                          >
                            <Lock size={14} />
                            <span>Submit for Admin Review</span>
                          </button>
                        </div>
                      ) : (
                        <button
                          onClick={handleSubmit}
                          disabled={submitting}
                          className="btn btn-primary"
                        >
                          <ShieldCheck size={16} />
                          <span>{submitting ? 'Submitting...' : 'Submit for Admin Review'}</span>
                        </button>
                      )}
                    </>
                  )}
                </div>
              </div>
            </div>
          )}
        </div>
      </div>
    </>
  )
}
